package com.rubik.plugins.basic

object LogTags {
    const val PUBLISH_CONTEXT_LIBS = "<RUBIK> PUBLISH_CONTEXT "
    const val PUBLISH_COMPONENTS = "<RUBIK> PUBLISH_COMPONENT "
    const val COMPUTE_CONTEXT_LIBS = "<RUBIK> COMPUTE_CONTEXT "
    const val TRANSFORM_CLASSES = "<RUBIK> TRANSFORM_CLASSES "
    const val CONTEXT_EXTENSION = "<RUBIK> CONTEXT_EXTENSION "
    const val ALL_TASKS = "<RUBIK> ALL_TASKS "
    const val PLUGIN = "<RUBIK> PLUGIN "
    const val TASK_GRAPHIC = "<RUBIK> TASK_GRAPHIC "
    const val PICK_CONTEXT = "<RUBIK> PICK_CONTEXT "
    const val MODULE_LINK = "<RUBIK> MODULE_LINK "
    const val CHECK_ROUTER_VERSION = "<RUBIK> CHECK_ROUTER_VERSION "

}