{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kotlin",
    "module": "blueprint",
    "version": "4.0.4-K1_5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "2yvx555ppzeb7lkgh7wwl5yscy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "blueprint-4.0.4-K1_5.jar",
          "url": "blueprint-4.0.4-K1_5.jar",
          "size": 117457,
          "sha512": "5c84a08b09e3b3bf412a6664a20d704170a486a660beea5b1cbaf440f348369a48f6f0945cd64dee2fd210896941f62fab53f65b11c1776c5819ddfaf72b2e54",
          "sha256": "9b80b7984a7aaf6808d1a870961612380467088db87e93cefe8951f9e2334203",
          "sha1": "b29d50eb88728a17141d89f014df32c485bb29ae",
          "md5": "e8181eda7f5ef5800f70406518d36979"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.ktnail",
          "module": "x",
          "version": {
            "requires": "0.0.3-K1_5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "blueprint-4.0.4-K1_5.jar",
          "url": "blueprint-4.0.4-K1_5.jar",
          "size": 117457,
          "sha512": "5c84a08b09e3b3bf412a6664a20d704170a486a660beea5b1cbaf440f348369a48f6f0945cd64dee2fd210896941f62fab53f65b11c1776c5819ddfaf72b2e54",
          "sha256": "9b80b7984a7aaf6808d1a870961612380467088db87e93cefe8951f9e2334203",
          "sha1": "b29d50eb88728a17141d89f014df32c485bb29ae",
          "md5": "e8181eda7f5ef5800f70406518d36979"
        }
      ]
    }
  ]
}
