{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kotlin",
    "module": "blueprint",
    "version": "4.0.4-K1_3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "fg3axsjbwnbmhkjguqu6wl2gtm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "blueprint-4.0.4-K1_3.jar",
          "url": "blueprint-4.0.4-K1_3.jar",
          "size": 115748,
          "sha512": "18c20c5f8cf775a03185ef6c973967c72f7b61a0dd2ea1731c6bbd823e2f2a9b256dcde001308c757dd4eca2b906e8d20147273339b4a5daa940ec57af4e13bf",
          "sha256": "8281e458fb964b902d057e8a527385423b4ba467cc537f3a5e0949b69965ff9f",
          "sha1": "466f72a2d059a4e569d6e4f8add4827753fef05e",
          "md5": "b40d6462c03f969342eed403705d627b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.ktnail",
          "module": "x",
          "version": {
            "requires": "0.0.3-K1_3"
          }
        }
      ],
      "files": [
        {
          "name": "blueprint-4.0.4-K1_3.jar",
          "url": "blueprint-4.0.4-K1_3.jar",
          "size": 115748,
          "sha512": "18c20c5f8cf775a03185ef6c973967c72f7b61a0dd2ea1731c6bbd823e2f2a9b256dcde001308c757dd4eca2b906e8d20147273339b4a5daa940ec57af4e13bf",
          "sha256": "8281e458fb964b902d057e8a527385423b4ba467cc537f3a5e0949b69965ff9f",
          "sha1": "466f72a2d059a4e569d6e4f8add4827753fef05e",
          "md5": "b40d6462c03f969342eed403705d627b"
        }
      ]
    }
  ]
}
