{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ktnail",
    "module": "gradle",
    "version": "0.1.1-AGBT4_2-K1_5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-0.1.1-AGBT4_2-K1_5.jar",
          "url": "gradle-0.1.1-AGBT4_2-K1_5.jar",
          "size": 67797,
          "sha512": "e8491aed729020df7f45cd64ae5ad7d408ad0a00897a19d6822802d39e844674e67f3fcc9a9e13acb33e87ec8301f5502e9fe22bfb92f0fc24c105f464eab27b",
          "sha256": "1dff1a8d8d29aeef1b2e2001eaec3ccfdf706edc66cc6f999af82f0299fef8c7",
          "sha1": "b2fa9b1fc44540716e10804b5821c18344d032f4",
          "md5": "0dc2e325b09d299162be1611ce90684e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.ktnail",
          "module": "x",
          "version": {
            "requires": "0.0.62-K1_5"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-0.1.1-AGBT4_2-K1_5.jar",
          "url": "gradle-0.1.1-AGBT4_2-K1_5.jar",
          "size": 67797,
          "sha512": "e8491aed729020df7f45cd64ae5ad7d408ad0a00897a19d6822802d39e844674e67f3fcc9a9e13acb33e87ec8301f5502e9fe22bfb92f0fc24c105f464eab27b",
          "sha256": "1dff1a8d8d29aeef1b2e2001eaec3ccfdf706edc66cc6f999af82f0299fef8c7",
          "sha1": "b2fa9b1fc44540716e10804b5821c18344d032f4",
          "md5": "0dc2e325b09d299162be1611ce90684e"
        }
      ]
    }
  ]
}
